services:
     tensorflow-gpu-jupyter:
          container_name: tensorflow-gpu-jupyter
          build:
               context: .
               dockerfile: ./tensorflow/Dockerfile
          tty: true
          volumes:
               - ./data/:/app/data
               - ./notebooks/:/app/notebooks
               - ./output/:/app/output
          deploy:
               resources:
                    reservations:
                         devices:
                              - driver: nvidia
                                count: 1
                                capabilities: [gpu]
          ports:
               - "$JUPYTER_PORT:$JUPYTER_PORT"
               - "$TENSORBOARD_PORT:$TENSORBOARD_PORT"
          env_file:
               - ./.env
          entrypoint: jupyter lab --ip 0.0.0.0 --port=$JUPYTER_PORT --no-browser --allow-root
